package com.aatout.enums;

public enum TypeName {
	AUTRE_COMPTE_D_IMPEYER,
	AUTRE_COMPTE_ET,
	AUTRE_TRESOR,
	AVANCE_SUR_ED,
	COMPTE_DE_PROVISIONS,
	COMPTE_D_IMPEYER_AVANCE_ED,	
	COMPTE_D_IMPEYER_ET,
	COMPTE_ECHANGE_A_TERME,
	COMPTE_TRESOR
}
